import React, { useEffect, useState } from 'react'
import Card from '../../components/Card/Card'
import DefaultLayout from '../../layouts/Default'
import Head from 'next/head'
const index = () => {

  const [cats, setCats] = useState([])
  const fetchCats = async () => {
    const response = await fetch('/api/cats')
    const data = await response.json();
    console.log(data)
    setCats(data)
  }
  useEffect(() => {
    fetchCats()
  }, [])
  return (
    <>
      <Head>
        <title>Our Cats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DefaultLayout>
        <div className="container mt-5">
          <div className="d-flex flex-wrap justify-content-between">

            {cats.map(cat => (
              <Card
                name={cat.name}
                id={cat.id}
                phone={cat.phone}
                image={cat.image}
                email={cat.email}
              />
            ))}
          </div>
        </div>
      </DefaultLayout>
    </>
  )
}

export default index